//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SignUp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccessCompany
    {
        public string AccessUid { get; set; }
        public string CompanyUid { get; set; }
        public int NoOfUsers { get; set; }
        public string PaymentDate { get; set; }
        public Nullable<int> PaymentPeriod { get; set; }
        public Nullable<decimal> PaymentAmount { get; set; }
        public string ExpiryDate { get; set; }
        public string LastUpdate { get; set; }
        public string UpdateBy { get; set; }
    }
}
