//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SignUp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccessUser
    {
        public string UserAccessUid { get; set; }
        public string UserUid { get; set; }
        public string CompanyUid { get; set; }
        public System.DateTime ActionDate { get; set; }
        public string Action { get; set; }
        public string Device { get; set; }
        public string DeviceType { get; set; }
        public string DeviceUserAgent { get; set; }
        public string DeviceOs { get; set; }
        public string DeviceOsVersion { get; set; }
        public string DeviceBrowser { get; set; }
        public string Latitude { get; set; }
        public string Longitude { get; set; }
        public string AppVersion { get; set; }
    }
}
