//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SignUp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChecklistMaster
    {
        public int CheckListId { get; set; }
        public string CompanyCode { get; set; }
        public string CheckListUID { get; set; }
        public string CheckListName { get; set; }
        public string CheckListCategory { get; set; }
        public string CheckListItem { get; set; }
        public string CheckListDescription { get; set; }
        public string AddedBy { get; set; }
        public string LastUpdate { get; set; }
        public string Warning { get; set; }
    }
}
