//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SignUp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Chemical
    {
        public string Id { get; set; }
        public string CompanyUid { get; set; }
        public string userCode { get; set; }
        public string ChemicalName { get; set; }
        public string Manufacturer { get; set; }
        public string SDSDate { get; set; }
        public string MaxQty { get; set; }
        public string OnSiteQty { get; set; }
        public string Labelled { get; set; }
        public string RiskAssessment { get; set; }
        public string Controls { get; set; }
        public string SafetySheet { get; set; }
        public string SafetyLink { get; set; }
        public string Comments { get; set; }
        public string LastCheck { get; set; }
        public string CheckBy { get; set; }
        public string AddedBy { get; set; }
        public string LastUpdate { get; set; }
        public string LastUpdateBy { get; set; }
    }
}
