//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SignUp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompanyDoc
    {
        public int CompanyDocId { get; set; }
        public string CompanyCode { get; set; }
        public string CompanySubFolder { get; set; }
        public string CompanyDocName { get; set; }
        public string CompanyDocType { get; set; }
        public string CompanyDocDescription { get; set; }
        public string AddedBy { get; set; }
        public string Date { get; set; }
    }
}
