//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SignUp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Company
    {
        public int CompanyId { get; set; }
        public Nullable<bool> IsParentCompany { get; set; }
        public int ParentCode { get; set; }
        public string CompanyCode { get; set; }
        public string CompanyName { get; set; }
        public string CompanyAddress1 { get; set; }
        public string CompanyAddress2 { get; set; }
        public string CompanyTown { get; set; }
        public Nullable<decimal> CompanyPostcode { get; set; }
        public string CompanyContactPerson { get; set; }
        public string CompanyContactEmail { get; set; }
        public string CompanyContactPhone { get; set; }
        public string CompanyContactPosition { get; set; }
        public string CompanyHSManager { get; set; }
        public string CompanyHSEmail { get; set; }
        public string ReportPerson1 { get; set; }
        public string ReportEmail1 { get; set; }
        public string ReportPerson2 { get; set; }
        public string ReportEmail2 { get; set; }
    }
}
