//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SignUp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompanyStaff
    {
        public int StaffId { get; set; }
        public string StaffName { get; set; }
        public string StaffSurname { get; set; }
        public string CompanyCode { get; set; }
        public string UserDepartmentCode { get; set; }
        public bool Inactive { get; set; }
        public string AddedBy { get; set; }
        public string LastUpdate { get; set; }
        public string AppUserId { get; set; }
    }
}
