//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SignUp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DailyBriefing
    {
        public string BriefingUid { get; set; }
        public string BriefingLocation { get; set; }
        public string BriefingDate { get; set; }
        public string BriefingCompletedBy { get; set; }
        public Nullable<bool> BriefingSafeToWork { get; set; }
        public string BriefingStartOne { get; set; }
        public string BriefingStarttwo { get; set; }
        public string BriefingStartThree { get; set; }
        public string BriefingEndOne { get; set; }
        public string BriefingEndTwo { get; set; }
        public string BriefingEndThree { get; set; }
        public Nullable<decimal> BriefingTotalHours { get; set; }
        public string BriefingComments { get; set; }
        public string BriefingCompanyUid { get; set; }
        public string BriefingAddedBy { get; set; }
        public string BriefingCreatedAt { get; set; }
        public Nullable<bool> BriefingChecked { get; set; }
        public string BriefingCheckedBy { get; set; }
        public Nullable<bool> BriefingDeleted { get; set; }
        public string BriefingDeletedBy { get; set; }
    }
}
