//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SignUp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FileData
    {
        public int Id { get; set; }
        public string ParentId { get; set; }
        public string ParentName { get; set; }
        public string SubFolder { get; set; }
        public string FileDescription { get; set; }
        public string FileTopic { get; set; }
        public string FileName { get; set; }
        public string FileExtension { get; set; }
        public string FileSize { get; set; }
        public string AddedBy { get; set; }
        public string Date { get; set; }
    }
}
