//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SignUp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class JSAData
    {
        public string TaskUid { get; set; }
        public string CompanyUid { get; set; }
        public string AddedByUid { get; set; }
        public string AddedByName { get; set; }
        public string JobName { get; set; }
        public string Date { get; set; }
        public string Location { get; set; }
        public string Sequence { get; set; }
        public string Hazard { get; set; }
        public string RiskBefore { get; set; }
        public string RecommendedActions { get; set; }
        public string RiskAfter { get; set; }
        public string Status { get; set; }
        public string AddedOn { get; set; }
        public string LastUpdate { get; set; }
        public string Latitude { get; set; }
        public string Longitude { get; set; }
        public Nullable<bool> Deleted { get; set; }
        public string DeletedBy { get; set; }
        public string JsaUid { get; set; }
        public string SequenceDescription { get; set; }
    }
}
