//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SignUp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class JSAReviewed
    {
        public string AcknowledgeUid { get; set; }
        public string JSAUid { get; set; }
        public string AcknowledgeBy { get; set; }
        public string AcknowledgeDate { get; set; }
        public string AddedBy { get; set; }
        public string AddedOn { get; set; }
        public string Comments { get; set; }
    }
}
