//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SignUp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LinkedProject
    {
        public int LinkedId { get; set; }
        public string ProjectCode { get; set; }
        public string UserCode { get; set; }
        public string LinkedBy { get; set; }
        public string Date { get; set; }
    }
}
