//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SignUp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Meeting
    {
        public int MeetingId { get; set; }
        public string MeetingCompanyCode { get; set; }
        public string MeetingType { get; set; }
        public string MeetingDate { get; set; }
        public string MeetingHeldBy { get; set; }
        public string MeetingNotes { get; set; }
        public string MeetingActionSteps { get; set; }
        public string AddedBy { get; set; }
        public string LastUpdate { get; set; }
        public string MeetingNotesOld { get; set; }
    }
}
