//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SignUp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectDoc
    {
        public int ProjectDocId { get; set; }
        public string ProjectCode { get; set; }
        public string ProjectSubFolder { get; set; }
        public string ProjectDocName { get; set; }
        public string ProjectDocType { get; set; }
        public string ProjectDocDescription { get; set; }
        public string AddedBy { get; set; }
        public string Date { get; set; }
    }
}
