//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SignUp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RiskRegister
    {
        public System.Guid RiskUid { get; set; }
        public string Risk { get; set; }
        public string PotentialRisk { get; set; }
        public Nullable<int> Likelihood { get; set; }
        public Nullable<int> Consequence { get; set; }
        public string RiskRating { get; set; }
        public Nullable<bool> EliminateControl { get; set; }
        public Nullable<bool> SubstituteControl { get; set; }
        public Nullable<bool> IsolateControl { get; set; }
        public Nullable<bool> EngineeringControl { get; set; }
        public Nullable<bool> AdministrationControl { get; set; }
        public Nullable<bool> PPEControl { get; set; }
        public string ControlDescription { get; set; }
        public string ResidualRisk { get; set; }
        public Nullable<bool> TrainingRequired { get; set; }
        public string FurtherActions { get; set; }
        public string PersonToAction { get; set; }
        public string DueDate { get; set; }
        public string DateCompleted { get; set; }
        public string DateChecked { get; set; }
        public string CheckedBy { get; set; }
        public string CompanyUid { get; set; }
        public string DateAdded { get; set; }
        public string AddedBy { get; set; }
        public string LastUpdate { get; set; }
        public string UpdateBy { get; set; }
        public Nullable<bool> Deleted { get; set; }
        public string DeletedBy { get; set; }
    }
}
