//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SignUp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stepback
    {
        public int LogId { get; set; }
        public string Reference { get; set; }
        public string AHeading { get; set; }
        public string A1Text { get; set; }
        public string A1Result { get; set; }
        public string A1Comment { get; set; }
        public string A2Text { get; set; }
        public string A2Result { get; set; }
        public string A2Comment { get; set; }
        public string A3Text { get; set; }
        public string A3Result { get; set; }
        public string A3Comment { get; set; }
        public string A4Text { get; set; }
        public string A4Result { get; set; }
        public string A4Comment { get; set; }
        public string A5Text { get; set; }
        public string A5Result { get; set; }
        public string A5Comment { get; set; }
        public string A6Text { get; set; }
        public string A6Result { get; set; }
        public string A6Comment { get; set; }
        public string A7Text { get; set; }
        public string A7Result { get; set; }
        public string A7Comment { get; set; }
        public string BHeading { get; set; }
        public string B1Text { get; set; }
        public string B1Result { get; set; }
        public string B1Comment { get; set; }
        public string B2Text { get; set; }
        public string B2Result { get; set; }
        public string B2Comment { get; set; }
        public string B3Text { get; set; }
        public string B3Result { get; set; }
        public string B3Comment { get; set; }
        public string B4Text { get; set; }
        public string B4Result { get; set; }
        public string B4Comment { get; set; }
        public string B5Text { get; set; }
        public string B5Result { get; set; }
        public string B5Comment { get; set; }
        public string B6Text { get; set; }
        public string B6Result { get; set; }
        public string B6Comment { get; set; }
        public string B7Text { get; set; }
        public string B7Result { get; set; }
        public string B7Comment { get; set; }
        public string B8Text { get; set; }
        public string B8Result { get; set; }
        public string B8Comment { get; set; }
        public string CHeading { get; set; }
        public string C1Text { get; set; }
        public string C1Result { get; set; }
        public string C1Comment { get; set; }
        public Nullable<bool> H_Spillage { get; set; }
        public Nullable<bool> H_Slips { get; set; }
        public Nullable<bool> H_ManualHandling { get; set; }
        public Nullable<bool> H_ConfinedSpace { get; set; }
        public Nullable<bool> H_Lifting { get; set; }
        public Nullable<bool> H_AccessWay { get; set; }
        public Nullable<bool> H_Vehicles { get; set; }
        public Nullable<bool> H_Heat { get; set; }
        public Nullable<bool> H_Lightning { get; set; }
        public Nullable<bool> H_WorkingAtHeights { get; set; }
        public Nullable<bool> H_Radiation { get; set; }
        public Nullable<bool> H_Vibration { get; set; }
        public Nullable<bool> H_Electrical { get; set; }
        public Nullable<bool> H_HazardousSubstances { get; set; }
        public Nullable<bool> H_Tools { get; set; }
        public Nullable<bool> H_FallingObjects { get; set; }
        public Nullable<bool> H_Dust { get; set; }
        public Nullable<bool> H_Pressure { get; set; }
        public Nullable<bool> H_Noise { get; set; }
        public Nullable<bool> H_GroundConditions { get; set; }
        public Nullable<bool> H_StoredEnergy { get; set; }
        public Nullable<bool> H_PinchPoint { get; set; }
        public string H_OtherHazards { get; set; }
        public string CompletionDate { get; set; }
        public string GeneralComments { get; set; }
        public string SupervisorCompany { get; set; }
        public string SupervisorName { get; set; }
        public string SupervisorSignature { get; set; }
        public string EmployeeCompany { get; set; }
        public string EmployeeName { get; set; }
        public string EmployeeSignature { get; set; }
        public string AddedBy { get; set; }
        public string CompanyCode { get; set; }
        public string AddedOn { get; set; }
        public Nullable<bool> Status { get; set; }
    }
}
