//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SignUp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Training
    {
        public int TrainingId { get; set; }
        public string UserId { get; set; }
        public string CourseName { get; set; }
        public string CourseDate { get; set; }
        public string ExpiryDate { get; set; }
        public string CompetencyLevel { get; set; }
        public string ProviderName { get; set; }
        public string LastUpdateBy { get; set; }
        public string UpdateDate { get; set; }
        public string StudentNumber { get; set; }
        public string NZQANumber { get; set; }
    }
}
