//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SignUp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserInfo
    {
        public int id { get; set; }
        public string Email { get; set; }
        public string UserId { get; set; }
        public string UserName { get; set; }
        public string LastName { get; set; }
        public string PhoneNumber { get; set; }
        public string Gender { get; set; }
        public string Age { get; set; }
        public string Notes { get; set; }
        public string Profile { get; set; }
        public string FirstName { get; set; }
        public string DateOfBirth { get; set; }
        public string BirthCountry { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string Suburb { get; set; }
        public string City { get; set; }
        public string OtherContact { get; set; }
        public string Occupation { get; set; }
        public string MaritalStatus { get; set; }
        public string MaritalState { get; set; }
        public Nullable<bool> FatherLiving { get; set; }
        public Nullable<bool> MotherLiving { get; set; }
        public string ParentProblems { get; set; }
        public string ParentMarriage { get; set; }
        public string ChildLife { get; set; }
        public string TeenageLife { get; set; }
        public string SixMonthLife { get; set; }
        public string FamilyComments { get; set; }
        public string MedicalNotes { get; set; }
        public string LastCheckup { get; set; }
        public string Checkupdate { get; set; }
        public Nullable<bool> OnMedication { get; set; }
        public string MedicationName { get; set; }
        public string MedicationReason { get; set; }
        public string PsycNotes { get; set; }
        public string PsycProblems { get; set; }
        public Nullable<bool> PsycPrevious { get; set; }
        public string PsycPreviousDates { get; set; }
        public string PsycPreviousTreated { get; set; }
        public string ViolenceScale { get; set; }
        public string ViolenceExplain { get; set; }
        public string GreatestFear { get; set; }
        public string GreatestHope { get; set; }
        public string SeekingHelpFor { get; set; }
        public string WhoKnows { get; set; }
        public string OutcomeWanted { get; set; }
        public string MeetingAssist { get; set; }
        public string AdditionalComments { get; set; }
        public string AdminNotes { get; set; }
        public Nullable<bool> PsycBreakdown { get; set; }
        public Nullable<bool> EmailReminder { get; set; }
        public Nullable<bool> Privacy { get; set; }
    }
}
