//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SignUp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VisitLog
    {
        public string VisitUid { get; set; }
        public string CompanyUid { get; set; }
        public string UserUid { get; set; }
        public string SiteUid { get; set; }
        public System.DateTime VisitTime { get; set; }
        public string Latitude { get; set; }
        public string Longitude { get; set; }
        public bool Result { get; set; }
        public string Notes { get; set; }
        public Nullable<System.DateTime> Created_at { get; set; }
        public string Created_by { get; set; }
        public string LastUpdate { get; set; }
    }
}
