//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SignUp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VisitRegister
    {
        public int VisitId { get; set; }
        public string CompanyCode { get; set; }
        public string UserCode { get; set; }
        public string DateIn { get; set; }
        public string DateOut { get; set; }
        public string Name { get; set; }
        public string Signature { get; set; }
        public string Company { get; set; }
        public string Purpose { get; set; }
        public string Comments { get; set; }
        public string WhoVisit { get; set; }
        public string TimeIn { get; set; }
        public string TimeOut { get; set; }
        public string SignatureOut { get; set; }
        public string DeviceId { get; set; }
        public string IsStaff { get; set; }
        public Nullable<bool> IsLogin { get; set; }
        public string Longitude { get; set; }
        public string Latitude { get; set; }
        public string DeviceType { get; set; }
    }
}
