//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SignUp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WebUser
    {
        public string UserId { get; set; }
        public string Username { get; set; }
        public string UserCompanyCode { get; set; }
        public string UserFirstName { get; set; }
        public string UserLastName { get; set; }
        public string UserEmail { get; set; }
        public string UserPhoneNumber { get; set; }
        public string UserDepartmentCode { get; set; }
        public string UserFunctionCode { get; set; }
        public string UserProfileCode { get; set; }
        public string UserAddedBy { get; set; }
        public Nullable<bool> UserNotActive { get; set; }
    }
}
